#ifndef FLIGHT_CONFIG_H
#define FLIGHT_CONFIG_H

#define FC_ONE_G_MPS2 9.80665f

#define FC_MS5611_I2C_ADDRESS 0x77u
#define FC_BNO085_I2C_ADDRESS 0x4Au

#define FC_ZED_F9P_RATE_HZ 15u

#define FC_LAUNCH_ACCEL_THRESHOLD_G 1.2f
#define FC_BURNOUT_ACCEL_THRESHOLD_G 0.5f
#define FC_DESCENT_ACCEL_THRESHOLD_G 1.0f

#define FC_BURNOUT_CONFIRM_MS 120u
#define FC_APOGEE_MIN_ALTITUDE_M 30.0f
#define FC_CM5_LINK_TIMEOUT_MS 250u

#define FC_MAX_LANDING_CROSSRANGE_M 50.0f
#define FC_MIN_RTK_SATELLITES 12u

#define FC_SUICIDE_BURN_ALTITUDE_OFFSET_M 1.0f
#define FC_SUICIDE_BURN_SAFETY_MARGIN_M 4.0f
#define FC_SECOND_STAGE_MAX_DECEL_MPS2 35.0f
#define FC_IGNITION_LATENCY_S 0.20f

#define FC_FLASH_LOG_SECTOR_SIZE 4096u
#define FC_FLASH_LOG_PAGE_SIZE 256u

#define FC_DEFAULT_WAYPOINT_X_M 0.0f
#define FC_DEFAULT_WAYPOINT_Y_M 0.0f

#endif
